// Generated by unit-tests/write.sh on {{TIMESTAMP}}
// Source under test: {{SOURCE_PATH}}

using Xunit;
// using {{MODULE}}.Namespace;

namespace {{MODULE}}.Tests;

public class {{MODULE}}Tests
{
    public {{MODULE}}Tests()
    {
        // arrange shared state in the constructor
    }

    [Fact(DisplayName = "happy path — TODO describe canonical behaviour")]
    public void HappyPath_Todo()
    {
        // arrange
        // act
        // assert
        Assert.True(true, "TODO: real assertion");
    }

    [Theory]
    [InlineData(0)]
    [InlineData(1)]
    [InlineData(2)]
    public void EdgeCases_Todo(int input)
    {
        // TODO
    }
}
