// vitest.config.ts — generated by unit-tests skill.
// SoTA defaults (May 2026): v8 coverage, strict thresholds, HTML + LCOV + JUnit.
import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    globals: true,
    environment: 'node',                 // change to 'jsdom' or 'happy-dom' for DOM tests
    include: ['**/*.{test,spec}.{ts,tsx,js,jsx}'],
    exclude: ['**/node_modules/**', '**/dist/**', '**/.next/**', '**/e2e/**'],

    coverage: {
      provider: 'v8',
      reporter: ['text', 'html', 'lcov', 'json-summary'],
      reportsDirectory: 'test-reports/js/coverage',
      include: ['app/**', 'components/**', 'lib/**', 'utils/**', 'hooks/**', 'store/**'],
      exclude: [
        '**/*.test.*', '**/*.spec.*', '**/__tests__/**', '**/__mocks__/**',
        '**/types/**', '**/*.d.ts', '**/index.ts',
      ],
      thresholds: {
        lines: {{THRESHOLD}},
        functions: {{THRESHOLD}},
        statements: {{THRESHOLD}},
        branches: {{THRESHOLD}},
      },
      all: true,                          // include uncovered files in the report
    },

    reporters: ['default', ['junit', { outputFile: 'test-reports/js/junit.xml' }]],

    testTimeout: 10_000,
    hookTimeout: 10_000,
  },
});
