use std::path::{Path, PathBuf};

pub const TEMPLATE_VERSION: u32 = 1;

// Marker contract: every generated CI file starts with this prefix on line 1.
// Presence is the signal that the file is managed by s5d; absence means the
// user owns it. The version number lets ci_check flag files generated by an
// older template.
fn marker_line(pkg_version: &str) -> String {
    format!(
        "# s5d-ci-template: v{} (generated by s5d {}; verify with s5d ci check)",
        TEMPLATE_VERSION, pkg_version
    )
}

pub fn github_workflow() -> String {
    let pkg_version = env!("CARGO_PKG_VERSION");
    let marker = marker_line(pkg_version);
    // Use placeholder substitution so the ${{ }} tokens are kept literal in
    // the output YAML and are not interpreted by Rust format!.
    let template = include_str!("ci_github_workflow.tpl");
    let body = template.replace("__S5D_VERSION__", pkg_version);
    format!("{}\n{}", marker, body)
}

pub fn gitlab_fragment() -> String {
    let pkg_version = env!("CARGO_PKG_VERSION");
    let marker = marker_line(pkg_version);
    let template = include_str!("ci_gitlab_fragment.tpl");
    let body = template.replace("__S5D_VERSION__", pkg_version);
    format!("{}\n{}", marker, body)
}

pub enum CiTarget {
    Github,
    Gitlab,
}

/// Write generated CI configs and return the paths written.
///
/// Overwrite rules:
/// - Managed file (starts with marker) → regenerate freely.
/// - User-owned file (exists, no marker) → bail unless `force`.
/// - No file → create.
pub fn ci_init(root: &Path, targets: &[CiTarget], force: bool) -> anyhow::Result<Vec<PathBuf>> {
    let mut written = Vec::new();

    for target in targets {
        match target {
            CiTarget::Github => {
                let workflow_dir = root.join(".github").join("workflows");
                std::fs::create_dir_all(&workflow_dir)?;
                let dest = workflow_dir.join("s5d.yml");
                write_managed_file(&dest, github_workflow(), force)?;
                written.push(dest);
            }
            CiTarget::Gitlab => {
                let ci_dir = root.join(".s5d").join("ci");
                std::fs::create_dir_all(&ci_dir)?;
                let fragment_dest = ci_dir.join("s5d.gitlab-ci.yml");
                write_managed_file(&fragment_dest, gitlab_fragment(), force)?;
                written.push(fragment_dest);

                // Create a stub .gitlab-ci.yml only when it doesn't exist yet.
                // If it already exists we return the path in written so the
                // caller can print a note — but we do NOT overwrite it.
                let root_ci = root.join(".gitlab-ci.yml");
                if !root_ci.exists() {
                    let pkg_version = env!("CARGO_PKG_VERSION");
                    let marker = marker_line(pkg_version);
                    let stub = format!(
                        "{}\ninclude:\n  - local: .s5d/ci/s5d.gitlab-ci.yml\n",
                        marker
                    );
                    std::fs::write(&root_ci, stub)?;
                    written.push(root_ci);
                }
                // else: caller checks written to know whether the stub was created
            }
        }
    }

    Ok(written)
}

fn write_managed_file(dest: &Path, content: String, force: bool) -> anyhow::Result<()> {
    if dest.exists() {
        let existing = std::fs::read_to_string(dest)?;
        let managed = existing
            .lines()
            .next()
            .unwrap_or("")
            .contains("s5d-ci-template:");
        if !managed && !force {
            anyhow::bail!(
                "user-owned file (no s5d-ci-template marker): {} — re-run with --force to overwrite",
                dest.display()
            );
        }
    }
    std::fs::write(dest, content)?;
    Ok(())
}

pub struct CiCheckReport {
    pub findings: Vec<String>,
    pub stale: bool,
}

/// Check every known generated path for staleness.
pub fn ci_check(root: &Path) -> anyhow::Result<CiCheckReport> {
    let candidates = [
        root.join(".github").join("workflows").join("s5d.yml"),
        root.join(".s5d").join("ci").join("s5d.gitlab-ci.yml"),
        root.join(".gitlab-ci.yml"),
    ];

    let mut findings = Vec::new();
    let mut stale = false;
    let mut any_found = false;

    for path in &candidates {
        if !path.exists() {
            continue;
        }
        let content = std::fs::read_to_string(path)?;
        let first_line = content.lines().next().unwrap_or("");

        if !first_line.contains("s5d-ci-template:") {
            findings.push(format!(
                "{}: unmanaged (no s5d-ci-template marker)",
                path.display()
            ));
            any_found = true;
            continue;
        }

        // Parse version: "# s5d-ci-template: vN ..."
        if let Some(v) = parse_marker_version(first_line) {
            any_found = true;
            if v < TEMPLATE_VERSION {
                findings.push(format!(
                    "{}: stale (v{} < v{}) — re-run s5d ci init",
                    path.display(),
                    v,
                    TEMPLATE_VERSION
                ));
                stale = true;
            }
        } else {
            findings.push(format!(
                "{}: unmanaged (no s5d-ci-template marker)",
                path.display()
            ));
            any_found = true;
        }
    }

    if !any_found {
        findings.push("no generated CI config — run s5d ci init".to_string());
    }

    Ok(CiCheckReport { findings, stale })
}

fn parse_marker_version(line: &str) -> Option<u32> {
    // Pattern: "# s5d-ci-template: vN ..."
    let rest = line.strip_prefix("# s5d-ci-template: v")?;
    let version_str = rest.split_whitespace().next()?;
    version_str.parse().ok()
}

/// Run built-in CI checks (validate, architecture, drift) — no gate_commands
/// or config-driven engines are executed. Fork-PR trust boundary: only
/// read-only checks that cannot be subverted by PR author.
///
/// Returns `Ok(true)` when all checks pass, `Ok(false)` on any failure
/// (caller should exit non-zero).
pub fn ci_exec(root: &Path) -> anyhow::Result<bool> {
    let Some(project) = crate::S5dProject::find(root) else {
        anyhow::bail!("no .s5d/ found — run s5d init first");
    };

    let specs = project.discover_specs()?;
    if specs.is_empty() {
        println!("s5d ci exec: no specs found, nothing to check");
        return Ok(true);
    }

    let mut all_passed = true;

    for (path, spec) in &specs {
        let filename = path.file_name().unwrap_or_default().to_string_lossy();

        // (a) Validate every spec
        let validate_errors = crate::validate::validate_spec(spec);
        if validate_errors.is_empty() {
            println!("  ok  [validate] {}", spec.id);
        } else {
            for e in &validate_errors {
                eprintln!("  error: [validate] {}: {}", spec.id, e);
            }
            all_passed = false;
        }

        // (b) Architecture check for specs with architecture gate
        if spec.gates.iter().any(|g| g.kind == "architecture") {
            match crate::architecture_check(spec, &project.root) {
                Ok(report) => {
                    if report.errors.is_empty() {
                        println!("  ok  [architecture] {}", spec.id);
                    } else {
                        for e in &report.errors {
                            eprintln!("  error: [architecture] {}: {}", spec.id, e);
                        }
                        all_passed = false;
                    }
                }
                Err(e) => {
                    eprintln!("  error: [architecture] {}: {}", spec.id, e);
                    all_passed = false;
                }
            }
        }

        // (c) Drift check for applied specs
        let record = project.load_record(&filename)?;
        let is_applied = record
            .as_ref()
            .is_some_and(|r| r.status == crate::models::SpecStatus::Applied);

        if is_applied {
            match crate::check_drift(&project, spec, &filename) {
                Ok(crate::DriftResult::Synced) => {
                    println!("  ok  [drift] {}", spec.id);
                }
                Ok(crate::DriftResult::Partial { policy, note }) => {
                    println!(
                        "  note: [drift] {} — partial drift tolerated by policy: {} ({})",
                        spec.id, policy, note
                    );
                }
                Ok(crate::DriftResult::Drifted { expected, actual }) => {
                    eprintln!(
                        "  error: [drift] {} — drifted (expected: {}, actual: {})",
                        spec.id, expected, actual
                    );
                    all_passed = false;
                }
                Ok(crate::DriftResult::Degraded { reason }) => {
                    eprintln!("  error: [drift] {} — degraded: {}", spec.id, reason);
                    all_passed = false;
                }
                Err(e) => {
                    eprintln!("  error: [drift] {}: {}", spec.id, e);
                    all_passed = false;
                }
            }
        }
    }

    if all_passed {
        println!("s5d ci exec: all checks passed ({} spec(s))", specs.len());
    } else {
        eprintln!("s5d ci exec: checks failed");
    }

    Ok(all_passed)
}
