// Generated by unit-tests/write.sh on {{TIMESTAMP}}
// Source under test: {{SOURCE_PATH}}
//
// Prefer inline #[cfg(test)] mod tests in the source file when the unit
// under test is a private function. Use this external file only for
// public-API integration-flavoured tests.

// use {{MODULE}}::*;

#[cfg(test)]
mod tests {
    // use super::*;

    #[test]
    fn happy_path_todo() {
        // arrange
        // act
        // assert
        assert!(true, "TODO: real assertion");
    }

    #[test]
    #[should_panic(expected = "TODO")]
    fn failure_mode_todo() {
        panic!("TODO");
    }

    // Parametric tests via rstest crate (add to Cargo.toml dev-deps):
    // use rstest::rstest;
    //
    // #[rstest]
    // #[case(0, 0)]
    // #[case(1, 1)]
    // fn parametric_todo(#[case] input: i32, #[case] expected: i32) {
    //     assert_eq!(input, expected);
    // }
}
