#!/usr/bin/env bash
# plan.sh — turn an analyze.sh report into a refactor plan.
# Output: markdown plan + (optional) an s5d decision spec skeleton.
#
# Plans are VERTICAL slices: each step is independently testable and reversible.
# No horizontal "do all DB changes, then all UI changes" sequences.
#
# Usage:
#   bash plan.sh                              # consume default analyze output
#   bash plan.sh --input /tmp/refactor.json   # from a stored analysis
#   bash plan.sh --output refactor-plan.md
#   bash plan.sh --decision-spec              # also emit .s5d/packages/<decision>.s5d.yaml

set -uo pipefail

SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ANALYZE="$SKILL_DIR/scripts/analyze.sh"
INPUT=""
OUTPUT="refactor-plan.md"
EMIT_DECISION=0

while [ $# -gt 0 ]; do
    case "$1" in
        --input)          INPUT="$2"; shift 2 ;;
        --output)         OUTPUT="$2"; shift 2 ;;
        --decision-spec)  EMIT_DECISION=1; shift ;;
        -h|--help)
            sed -n '2,12p' "${BASH_SOURCE[0]}" | sed 's/^# \?//'
            exit 0
            ;;
        *) echo "unknown arg: $1" >&2; exit 2 ;;
    esac
done

if [ -z "$INPUT" ]; then
    INPUT=$(mktemp)
    trap 'rm -f "$INPUT"' EXIT
    bash "$ANALYZE" > "$INPUT" || { echo "analyze.sh failed" >&2; exit 2; }
fi

[ ! -f "$INPUT" ] && { echo "no analyze report at $INPUT" >&2; exit 2; }

# Need python3 for JSON parsing in plan emission (bash JSON is hellish).
command -v python3 >/dev/null 2>&1 || { echo "python3 required for plan.sh" >&2; exit 2; }

if [ -e "$OUTPUT" ]; then
    OUTPUT="${OUTPUT}.new"
    echo "→ output exists; writing to $OUTPUT" >&2
fi

python3 - "$INPUT" > "$OUTPUT" <<'PYEOF'
import json, sys, datetime

with open(sys.argv[1]) as f:
    data = json.load(f)

now = datetime.datetime.utcnow().strftime("%Y-%m-%d")
violations = data.get("violations", [])
summary = data.get("summary", {})

def by_kind(k):
    return [v for v in violations if v["kind"] == k]

god = by_kind("god-component")
drift = by_kind("drift-missing")
mc = by_kind("missing-contract")
orphan = by_kind("orphan")
capdup = by_kind("capability-dup")
leak = by_kind("domain-leak")

# Sort god-components: unsafe first (need tests before refactor),
# then by exports count descending.
def god_sort_key(v):
    safety_rank = {"unsafe": 0, "risky": 1, "safe": 2}.get(v["safety"], 3)
    # Extract export count from detail string
    import re
    m = re.search(r"exports=(\d+)", v["detail"])
    exports = int(m.group(1)) if m else 0
    return (safety_rank, -exports)

god.sort(key=god_sort_key)

print(f"# Refactor Plan — {now}")
print("")
print(f"Generated by `domain-refactor/scripts/plan.sh` from `{data['map']}`.")
print(f"Total violations: **{summary.get('total', 0)}**.")
print("")
print("## Summary")
print("")
print("| Kind | Count | Severity |")
print("|---|---:|---|")
for kind, sev in [("god-component", "high"), ("domain-leak", "high"),
                   ("capability-dup", "high"), ("drift-missing", "medium"),
                   ("missing-contract", "medium"), ("orphan", "info")]:
    print(f"| {kind} | {summary.get(kind, 0)} | {sev} |")
print("")
print("## Prerequisites")
print("")
print("Before applying any step:")
print("- ✅ Working tree is clean (`git status` empty).")
print("- ✅ Unit tests pass with no decrease in coverage (`bash ~/.agents/skills/unit-tests/scripts/run.sh`).")
print("- ✅ E2E specs exist for the affected use cases (`bash ~/.agents/skills/e2e-tests/scripts/coverage.sh`).")
print("- ✅ s5d decision recorded for any refactor ≥ 30 LOC (see AGENTS.md).")
print("")
print("## Vertical slices")
print("")
print("Each slice is **atomic** — one logical move with a testable checkpoint at the end.")
print("Apply via `bash ~/.agents/skills/domain-refactor/scripts/apply.sh <slice-id>`,")
print("then `bash verify.sh` before moving to the next slice.")
print("")

slice_id = 0

# --- 1. Capability duplications (fix the map first, no code touched yet) ---
if capdup:
    slice_id += 1
    print(f"### Slice {slice_id} — Fix capability duplication in the map")
    print("")
    print("**Severity:** high. **Touches code:** no, only `.s5d/discovery/architecture-map.md`.")
    print("")
    for v in capdup:
        print(f"- `{v['path']}` — {v['detail']}")
    print("")
    print("**Action:** rename one of the duplicate capabilities to a distinct id. Document the renaming in the same commit. Re-run `analyze.sh` to confirm the duplication is gone.")
    print("")

# --- 2. Drift-missing (file gone but in map) — fix the map ---
if drift:
    slice_id += 1
    print(f"### Slice {slice_id} — Resolve drift in §5 Components")
    print("")
    print("**Severity:** medium. **Touches code:** no.")
    print("")
    for v in drift:
        print(f"- `{v['path']}` — {v['detail']}")
    print("")
    print("**Action:** for each entry, either restore the file (if intent was to keep it) or remove the row from the map (if intent was to delete). Brace-expansion shorthand (e.g. `{x,y}.ts`) should be expanded into one row per file.")
    print("")

# --- 3. Missing contracts — add explicit interface ---
if mc:
    slice_id += 1
    print(f"### Slice {slice_id} — Add explicit contracts to cross-domain edges")
    print("")
    print("**Severity:** medium. **Touches code:** yes — adds type / interface files.")
    print("")
    for v in mc:
        print(f"- {v['path']} — {v['detail']}")
    print("")
    print("**Action:** define an interface / type / protobuf for each edge (downstream domain owns the consumer-facing shape). Land each edge in its own commit. Acceptance: `tsc --noEmit` passes and the downstream component imports the contract, not the upstream implementation.")
    print("")

# --- 4. God-components — biggest leverage refactor ---
if god:
    print(f"### Slice {slice_id + 1}.. — Decompose god-components (one per slice)")
    print("")
    print("Each god-component is its own vertical slice. **Always start with the SAFE ones**; UNSAFE ones need tests first.")
    print("")
    for v in god:
        slice_id += 1
        safety = v["safety"]
        safety_emoji = {"safe": "🟢", "risky": "🟡", "unsafe": "🔴"}.get(safety, "⚪")
        print(f"#### Slice {slice_id} — `{v['path']}` {safety_emoji} {safety}")
        print("")
        print(f"**Detail:** {v['detail']}")
        print("")
        if safety == "unsafe":
            print(f"**🔴 STOP — write tests first.** This file has coverage < 30% and no e2e spec referencing it. Refactoring without tests is unverifiable. Steps:")
            print(f"  1. `bash ~/.agents/skills/unit-tests/scripts/write.sh {v['path']}` — scaffold a test file.")
            print(f"  2. Fill in tests for each exported function. Land in a separate commit.")
            print(f"  3. Re-run `analyze.sh` — file should be 'safe' or 'risky' before continuing.")
            print(f"  4. Then come back to this slice and decompose.")
            print("")
        elif safety == "risky":
            print(f"**🟡 Risky — augment tests then refactor.** Coverage exists but is incomplete.")
            print(f"  1. Identify uncovered exports via the LCOV report (`open test-reports/js/coverage/index.html`).")
            print(f"  2. Add tests for uncovered paths. Land in a separate commit.")
            print(f"  3. Decompose: split into ≤ 5 files, each owning one cohesive capability.")
            print("")
        else:
            print(f"**🟢 Safe — decompose freely.** Test net catches regressions.")
            print(f"  1. Identify the natural seams (one capability per resulting file).")
            print(f"  2. Move each export to its own file; preserve public API via barrel file.")
            print(f"  3. Update `architecture-map.md` §5 with the new component rows in the SAME commit.")
            print("")
        print(f"**Acceptance:**")
        print(f"  - `tsc --noEmit && bash ~/.agents/skills/unit-tests/scripts/run.sh` passes.")
        print(f"  - `bash ~/.agents/skills/e2e-tests/scripts/coverage.sh` does not drop.")
        print(f"  - `bash ~/.agents/skills/domain-refactor/scripts/analyze.sh` no longer flags this file.")
        print("")

# --- 5. Orphans — informational ---
if orphan:
    slice_id += 1
    print(f"### Slice {slice_id} — Register substantial orphans (information only)")
    print("")
    print(f"**Severity:** info. **Touches code:** no, only the map.")
    print(f"**Count:** {len(orphan)} files ≥ 200 lines not registered in §5.")
    print("")
    print("The architecture map is intentionally a SELECTION, not exhaustive. Use this list to decide which files are worth promoting to canonical components. Heuristic: register a file if other agents need to find it via `trace.sh` or if it's a boundary owner.")
    print("")
    if orphan[:10]:
        print("Top 10 by line count:")
        sorted_orphans = sorted(orphan, key=lambda v: int(v["detail"].split()[0]), reverse=True)
        for v in sorted_orphans[:10]:
            print(f"- `{v['path']}` — {v['detail']}")
    print("")

print("## Apply order")
print("")
print("1. Slices that touch only the map (capability-dup, drift-missing, orphans) — no code risk, no test gates needed.")
print("2. Contract slices — type-safety net for code refactors.")
print("3. SAFE god-components first — quick wins, tests catch regressions.")
print("4. RISKY god-components after adding focused tests.")
print("5. UNSAFE god-components LAST, only after tests bring them to safe/risky.")
print("")
print("After each slice: `bash ~/.agents/skills/domain-refactor/scripts/verify.sh` MUST pass. Otherwise: rollback the slice and diagnose.")
PYEOF

echo "✓ wrote $OUTPUT" >&2

if [ "$EMIT_DECISION" -eq 1 ]; then
    PRODUCT="${S5D_PRODUCT:-$(basename "$(pwd)")}"
    DEC_ID="decision.domain-refactor"
    QUESTION="How should we sequence the refactor of god-components and resolve drift in the architecture map, given the current test coverage profile?"

    if command -v s5d >/dev/null 2>&1; then
        # Ensure .s5d/ exists in cwd (s5d new requires it).
        if [ ! -d ".s5d" ]; then
            s5d init >/dev/null 2>&1 || true
        fi

        S5D_NEW_OUT=$(s5d new "$DEC_ID" --tier decision --product "$PRODUCT" --question "$QUESTION" 2>&1)
        DSPEC=$(printf '%s\n' "$S5D_NEW_OUT" | grep "^ok Created spec:" | sed 's/^ok Created spec: //')

        if [ -z "$DSPEC" ]; then
            echo "error: s5d new did not emit a spec path. Output was:" >&2
            echo "$S5D_NEW_OUT" >&2
            exit 1
        fi

        # Add the three canonical hypotheses for domain-refactor sequencing.
        s5d decision add-hypothesis "$DSPEC" \
            --title "safe-first" \
            --content "Refactor SAFE god-components now (coverage sufficient), defer UNSAFE ones until tests exist. Lowest blast radius." \
            --scope "god-component decomposition order" >/dev/null 2>&1
        s5d decision add-hypothesis "$DSPEC" \
            --title "test-first" \
            --content "Write tests for ALL god-components before any refactor move, regardless of current coverage. Maximises safety but delays delivery." \
            --scope "god-component decomposition order" >/dev/null 2>&1
        s5d decision add-hypothesis "$DSPEC" \
            --title "extract-shared-contract" \
            --content "Introduce typed interfaces across domain edges before any code move, so refactor moves can lean on the type-checker as a regression guard." \
            --scope "domain-edge contract enforcement" >/dev/null 2>&1

        echo "✓ wrote $DSPEC" >&2
        echo "  next: review with the s5d skill — s5d_preview / s5d_decide via MCP" >&2
        echo "  (s5d_decide requires human confirmation — not called by this script)" >&2
    else
        # ── FALLBACK: s5d not on PATH — write a clearly-marked draft YAML ──────
        echo "warning: s5d binary not found on PATH — emitting unvalidated DRAFT yaml" >&2
        echo "         install s5d and re-run with --decision-spec to get a schema-valid spec." >&2

        DSPEC=".s5d/packages/${DEC_ID}.s5d.yaml"
        if [ -e "$DSPEC" ]; then
            DSPEC="${DSPEC}.new"
            echo "→ decision spec exists; writing to $DSPEC" >&2
        fi
        mkdir -p .s5d/packages
        NOW=$(date -u +%Y-%m-%dT%H:%M:%SZ)
        cat > "$DSPEC" <<YAMLEOF
# DRAFT — generated without s5d CLI (binary not on PATH).
# This file uses an UNVALIDATED schema. Run plan.sh --decision-spec again
# with s5d installed to produce a schema-valid spec.
schema: '1.0'
id: ${DEC_ID}
tier: decision
product: ${PRODUCT}
question: |
  ${QUESTION}
created_at: '${NOW}'
context: |
  analyze.sh surfaced N violations across god-component, drift-missing,
  missing-contract, orphan, capability-dup. See refactor-plan.md for the
  vertical-slice plan derived from this analysis.

  Hypotheses to evaluate (add via s5d_add_hypothesis):
  - safe-first: refactor SAFE god-components now, defer UNSAFE until tests exist.
  - test-first: write tests for ALL god-components before any refactor.
  - extract-shared-contract: introduce typed interfaces across domain edges
    before any code move, so refactor moves can lean on type-check.
YAMLEOF
        echo "✓ wrote $DSPEC (DRAFT — unvalidated)" >&2
    fi
fi
