#!/usr/bin/env bash
# plan.sh — turn an analyze.sh report into a refactor plan.
# Output: markdown plan + (optional) an s5d decision spec skeleton.
#
# Plans are VERTICAL slices: each step is independently testable and reversible.
# No horizontal "do all DB changes, then all UI changes" sequences.
#
# Usage:
#   bash plan.sh                              # consume default analyze output
#   bash plan.sh --input /tmp/refactor.json   # from a stored analysis
#   bash plan.sh --output refactor-plan.md
#   bash plan.sh --decision-spec              # also emit .s5d/packages/<decision>.s5d.yaml

set -uo pipefail

SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ANALYZE="$SKILL_DIR/scripts/analyze.sh"
INPUT=""
OUTPUT="refactor-plan.md"
EMIT_DECISION=0

need_val() { [ "$2" -ge 2 ] || { echo "$1 requires a value" >&2; exit 2; }; }

while [ $# -gt 0 ]; do
    case "$1" in
        --input)          need_val "$1" "$#"; INPUT="$2"; shift 2 ;;
        --output)         need_val "$1" "$#"; OUTPUT="$2"; shift 2 ;;
        --decision-spec)  EMIT_DECISION=1; shift ;;
        -h|--help)
            sed -n '2,12p' "${BASH_SOURCE[0]}" | sed 's/^# \?//'
            exit 0
            ;;
        *) echo "unknown arg: $1" >&2; exit 2 ;;
    esac
done

# Single EXIT trap for all temp files: bash traps don't stack, so a second
# `trap ... EXIT` later would silently drop this one and leak the input temp.
INPUT_TMP=""
PLAN_TMP=""
trap 'rm -f "$INPUT_TMP" "$PLAN_TMP"' EXIT

if [ -z "$INPUT" ]; then
    INPUT=$(mktemp)
    INPUT_TMP="$INPUT"
    bash "$ANALYZE" > "$INPUT" || { echo "analyze.sh failed" >&2; exit 2; }
fi

[ ! -f "$INPUT" ] && { echo "no analyze report at $INPUT" >&2; exit 2; }

# Need python3 for JSON parsing in plan emission (bash JSON is hellish).
command -v python3 >/dev/null 2>&1 || { echo "python3 required for plan.sh" >&2; exit 2; }

if [ -e "$OUTPUT" ]; then
    OUTPUT="${OUTPUT}.new"
    echo "→ output exists; writing to $OUTPUT" >&2
fi

# Generate into a temp file, not directly over $OUTPUT: a malformed/older analyze
# report can crash the python mid-stream, and `> "$OUTPUT"` would have already
# truncated it, leaving a partial file that the script then blesses with ✓
# (tribunal: partial-output-after-truncate). Atomic move only on success.
PLAN_TMP=$(mktemp)
if ! python3 - "$INPUT" > "$PLAN_TMP" <<'PYEOF'
import json, sys, datetime, re, shlex

with open(sys.argv[1]) as f:
    data = json.load(f)

# analyze.sh fields (paths, details) are derived from repo contents — a hostile
# repo can carry backticks/links/HTML in a filename or detail string. Neutralize
# control + markdown metacharacters so they can't break out of inline-code spans
# or inject link/HTML payloads into this plan (read downstream by agents/reviewers).
# (tribunal 2026-05-30, MED: plan.sh markdown/prompt injection.)
_CTRL_RE = re.compile(r"[\x00-\x1f\x7f]")
def san(s):
    s = _CTRL_RE.sub(" ", str(s))      # newlines + control chars -> space
    s = s.replace("`", "'")            # cannot close an inline-code span / open a fence
    s = s.replace("<", "\\<").replace(">", "\\>")  # no raw HTML
    s = s.replace("](", "]\\(")        # no [text](payload) link/image injection
    return s.strip()

def shq(s):
    # For a path interpolated into a COPYABLE shell command that ALSO sits inside a
    # markdown inline-code span. Two hazards, two defenses:
    #   - shell paste: shlex.quote handles spaces, dashes, quotes, ;, $().
    #   - markdown span: shlex alone still leaves backticks/newlines from a hostile
    #     path, which close the `code` span and inject layout (tribunal round-3).
    # So strip control chars + backticks first, then shell-quote the result.
    s = _CTRL_RE.sub(" ", str(s)).replace("`", "")
    return shlex.quote(s)

now = datetime.datetime.utcnow().strftime("%Y-%m-%d")
violations = data.get("violations", [])
summary = data.get("summary", {})

def by_kind(k):
    return [v for v in violations if v["kind"] == k]

god = by_kind("god-component")
drift = by_kind("drift-missing")
mc = by_kind("missing-contract")
orphan = by_kind("orphan")
capdup = by_kind("capability-dup")
leak = by_kind("domain-leak")

# Sort god-components: unsafe first (need tests before refactor),
# then by exports count descending.
def god_sort_key(v):
    safety_rank = {"unsafe": 0, "risky": 1, "safe": 2}.get(v["safety"], 3)
    # Extract export count from detail string
    import re
    m = re.search(r"exports=(\d+)", v["detail"])
    exports = int(m.group(1)) if m else 0
    return (safety_rank, -exports)

god.sort(key=god_sort_key)

print(f"# Refactor Plan — {now}")
print("")
print(f"Generated by `domain-refactor/scripts/plan.sh` from `{san(data['map'])}`.")
print(f"Total violations: **{summary.get('total', 0)}**.")
print("")
print("## Summary")
print("")
print("| Kind | Count | Severity |")
print("|---|---:|---|")
for kind, sev in [("god-component", "high"), ("domain-leak", "high"),
                   ("capability-dup", "high"), ("drift-missing", "medium"),
                   ("missing-contract", "medium"), ("orphan", "info")]:
    print(f"| {kind} | {summary.get(kind, 0)} | {sev} |")
print("")
print("## Prerequisites")
print("")
print("Before applying any step:")
print("- ✅ Working tree is clean (`git status` empty).")
print("- ✅ Unit tests pass with no decrease in coverage (`bash ~/.agents/skills/unit-tests/scripts/run.sh`).")
print("- ✅ E2E specs exist for the affected use cases (`bash ~/.agents/skills/e2e-tests/scripts/coverage.sh`).")
print("- ✅ s5d decision recorded for any refactor ≥ 30 LOC (see AGENTS.md).")
print("")
print("## Vertical slices")
print("")
print("Each slice is **atomic** — one logical move with a testable checkpoint at the end.")
print("Apply via `bash ~/.agents/skills/domain-refactor/scripts/apply.sh <slice-id>`,")
print("then `bash verify.sh` before moving to the next slice.")
print("")

slice_id = 0

# --- 1. Capability duplications (fix the map first, no code touched yet) ---
if capdup:
    slice_id += 1
    print(f"### Slice {slice_id} — Fix capability duplication in the map")
    print("")
    print("**Severity:** high. **Touches code:** no, only `.s5d/discovery/architecture-map.md`.")
    print("")
    for v in capdup:
        print(f"- `{san(v['path'])}` — {san(v['detail'])}")
    print("")
    print("**Action:** rename one of the duplicate capabilities to a distinct id. Document the renaming in the same commit. Re-run `analyze.sh` to confirm the duplication is gone.")
    print("")

# --- 2. Drift-missing (file gone but in map) — fix the map ---
if drift:
    slice_id += 1
    print(f"### Slice {slice_id} — Resolve drift in §5 Components")
    print("")
    print("**Severity:** medium. **Touches code:** no.")
    print("")
    for v in drift:
        print(f"- `{san(v['path'])}` — {san(v['detail'])}")
    print("")
    print("**Action:** for each entry, either restore the file (if intent was to keep it) or remove the row from the map (if intent was to delete). Brace-expansion shorthand (e.g. `{x,y}.ts`) should be expanded into one row per file.")
    print("")

# --- 3. Missing contracts — add explicit interface ---
if mc:
    slice_id += 1
    print(f"### Slice {slice_id} — Add explicit contracts to cross-domain edges")
    print("")
    print("**Severity:** medium. **Touches code:** yes — adds type / interface files.")
    print("")
    for v in mc:
        print(f"- {san(v['path'])} — {san(v['detail'])}")
    print("")
    print("**Action:** define an interface / type / protobuf for each edge (downstream domain owns the consumer-facing shape). Land each edge in its own commit. Acceptance: `tsc --noEmit` passes and the downstream component imports the contract, not the upstream implementation.")
    print("")

# --- 4. God-components — biggest leverage refactor ---
if god:
    print(f"### Slice {slice_id + 1}.. — Decompose god-components (one per slice)")
    print("")
    print("Each god-component is its own vertical slice. **Always start with the SAFE ones**; UNSAFE ones need tests first.")
    print("")
    for v in god:
        slice_id += 1
        safety = v["safety"]
        safety_emoji = {"safe": "🟢", "risky": "🟡", "unsafe": "🔴"}.get(safety, "⚪")
        print(f"#### Slice {slice_id} — `{san(v['path'])}` {safety_emoji} {safety}")
        print("")
        print(f"**Detail:** {san(v['detail'])}")
        print("")
        if safety == "unsafe":
            print(f"**🔴 STOP — write tests first.** This file has coverage < 30% and no e2e spec referencing it. Refactoring without tests is unverifiable. Steps:")
            print(f"  1. `bash ~/.agents/skills/unit-tests/scripts/write.sh {shq(v['path'])}` — scaffold a test file.")
            print(f"  2. Fill in tests for each exported function. Land in a separate commit.")
            print(f"  3. Re-run `analyze.sh` — file should be 'safe' or 'risky' before continuing.")
            print(f"  4. Then come back to this slice and decompose.")
            print("")
        elif safety == "risky":
            print(f"**🟡 Risky — augment tests then refactor.** Coverage exists but is incomplete.")
            print(f"  1. Identify uncovered exports via the LCOV report (`open test-reports/js/coverage/index.html`).")
            print(f"  2. Add tests for uncovered paths. Land in a separate commit.")
            print(f"  3. Decompose: split into ≤ 5 files, each owning one cohesive capability.")
            print("")
        else:
            print(f"**🟢 Safe — decompose freely.** Test net catches regressions.")
            print(f"  1. Identify the natural seams (one capability per resulting file).")
            print(f"  2. Move each export to its own file; preserve public API via barrel file.")
            print(f"  3. Update `architecture-map.md` §5 with the new component rows in the SAME commit.")
            print("")
        print(f"**Acceptance:**")
        print(f"  - `tsc --noEmit && bash ~/.agents/skills/unit-tests/scripts/run.sh` passes.")
        print(f"  - `bash ~/.agents/skills/e2e-tests/scripts/coverage.sh` does not drop.")
        print(f"  - `bash ~/.agents/skills/domain-refactor/scripts/analyze.sh` no longer flags this file.")
        print("")

# --- 5. Orphans — informational ---
if orphan:
    slice_id += 1
    print(f"### Slice {slice_id} — Register substantial orphans (information only)")
    print("")
    print(f"**Severity:** info. **Touches code:** no, only the map.")
    print(f"**Count:** {len(orphan)} files ≥ 200 lines not registered in §5.")
    print("")
    print("The architecture map is intentionally a SELECTION, not exhaustive. Use this list to decide which files are worth promoting to canonical components. Heuristic: register a file if other agents need to find it via `trace.sh` or if it's a boundary owner.")
    print("")
    if orphan[:10]:
        print("Top 10 by line count:")
        sorted_orphans = sorted(orphan, key=lambda v: int(v["detail"].split()[0]), reverse=True)
        for v in sorted_orphans[:10]:
            print(f"- `{san(v['path'])}` — {san(v['detail'])}")
    print("")

print("## Apply order")
print("")
print("1. Slices that touch only the map (capability-dup, drift-missing, orphans) — no code risk, no test gates needed.")
print("2. Contract slices — type-safety net for code refactors.")
print("3. SAFE god-components first — quick wins, tests catch regressions.")
print("4. RISKY god-components after adding focused tests.")
print("5. UNSAFE god-components LAST, only after tests bring them to safe/risky.")
print("")
print("After each slice: `bash ~/.agents/skills/domain-refactor/scripts/verify.sh` MUST pass. Otherwise: rollback the slice and diagnose.")
PYEOF
then
    echo "error: plan generation failed (malformed analyze report?) — $OUTPUT left untouched" >&2
    exit 1
fi
mv "$PLAN_TMP" "$OUTPUT"

echo "✓ wrote $OUTPUT" >&2

if [ "$EMIT_DECISION" -eq 1 ]; then
    PRODUCT="${S5D_PRODUCT:-$(basename "$(pwd)")}"
    DEC_ID="decision.domain-refactor"
    QUESTION="How should we sequence the refactor of god-components and resolve drift in the architecture map, given the current test coverage profile?"

    # The s5d CLI is the only path. The previous fallback wrote a raw, UNVALIDATED
    # YAML spec by interpolating $PRODUCT/$QUESTION into a heredoc — same class as the
    # adr.sh YAML-injection HIGH (tribunal 2026-05-30). The suite ships WITH the CLI, so
    # require it instead of emitting an injectable draft.
    if ! command -v s5d >/dev/null 2>&1; then
        echo "error: s5d CLI not found on PATH — cannot emit a schema-valid decision spec." >&2
        echo "  plan.sh --decision-spec routes through the s5d CLI by design. Install it first:" >&2
        echo "    git clone https://github.com/system5-dev/s5d && cd s5d && ./install.sh" >&2
        exit 127
    fi

    # Ensure .s5d/ exists in cwd (s5d new requires it).
    if [ ! -d ".s5d" ]; then
        s5d init >/dev/null 2>&1 || true
    fi

    S5D_NEW_OUT=$(s5d new "$DEC_ID" --tier decision --product "$PRODUCT" --question "$QUESTION" 2>&1)
    S5D_NEW_RC=$?

    # Primary: documented "ok Created spec: <path>" line. Fallback: deterministic
    # id glob, so a mismatched/older installed binary that still writes the spec is
    # recovered instead of crashing on a hard-coded output string.
    DSPEC=$(printf '%s\n' "$S5D_NEW_OUT" | sed -n 's/^ok Created spec: //p' | head -1)
    if [ -z "$DSPEC" ]; then
        DSPEC=$(ls -t .s5d/packages/"${DEC_ID}"__*.s5d.yaml 2>/dev/null | head -1)
    fi

    if [ "$S5D_NEW_RC" -ne 0 ] || [ -z "$DSPEC" ] || [ ! -f "$DSPEC" ]; then
        echo "error: s5d new failed (rc=$S5D_NEW_RC) or produced no spec. Output was:" >&2
        echo "$S5D_NEW_OUT" >&2
        echo "hint: a killed/stale installed s5d looks like this — reinstall: ./install.sh" >&2
        exit 1
    fi

    # add-hypothesis failures must NOT be swallowed: a spec missing a hypothesis is
    # partial state, and printing ✓ over it hides the corruption (tribunal MED #3).
    # Suppress stdout (the spec echo) but let stderr surface for diagnosis.
    add_hyp() {  # add_hyp <title> <content> <scope>
        if ! s5d decision add-hypothesis "$DSPEC" \
                --title "$1" --content "$2" --scope "$3" >/dev/null; then
            echo "error: add-hypothesis '$1' failed" >&2
            return 1
        fi
    }

    hyp_fail=0
    add_hyp "safe-first" \
        "Refactor SAFE god-components now (coverage sufficient), defer UNSAFE ones until tests exist. Lowest blast radius." \
        "god-component decomposition order" || hyp_fail=1
    add_hyp "test-first" \
        "Write tests for ALL god-components before any refactor move, regardless of current coverage. Maximises safety but delays delivery." \
        "god-component decomposition order" || hyp_fail=1
    add_hyp "extract-shared-contract" \
        "Introduce typed interfaces across domain edges before any code move, so refactor moves can lean on the type-checker as a regression guard." \
        "domain-edge contract enforcement" || hyp_fail=1

    if [ "$hyp_fail" -ne 0 ]; then
        echo "error: spec $DSPEC is partial — one or more hypotheses failed to add." >&2
        echo "       Inspect/repair it before relying on it; not printing success." >&2
        exit 1
    fi

    echo "✓ wrote $DSPEC" >&2
    echo "  next: review with the s5d skill — s5d_preview / s5d_decide via MCP" >&2
    echo "  (s5d_decide requires human confirmation — not called by this script)" >&2
fi
