// playwright.config.ts — generated by e2e-tests skill.
// SoTA defaults (2026): cross-browser projects, trace/video on retry, JUnit + HTML reports.
import { defineConfig, devices } from '@playwright/test';

const BASE_URL = process.env.PLAYWRIGHT_BASE_URL || '{{BASE_URL}}';

export default defineConfig({
  testDir: './e2e',
  testMatch: ['**/*.spec.ts', '**/*.spec.tsx', '**/*.spec.js'],
  testIgnore: ['**/api/**'],            // api project handles those

  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 2 : undefined,
  timeout: 60_000,
  expect: { timeout: 10_000 },

  reporter: [
    ['list'],
    ['html', { outputFolder: 'test-reports/e2e/web/html', open: 'never' }],
    ['junit', { outputFile: 'test-reports/e2e/web/junit.xml' }],
  ],

  use: {
    baseURL: BASE_URL,
    trace: 'on-first-retry',           // .zip trace for the trace viewer
    video: 'retain-on-failure',
    screenshot: 'only-on-failure',
    actionTimeout: 15_000,
    navigationTimeout: 30_000,
  },

  projects: [
    { name: 'chromium', use: { ...devices['Desktop Chrome'] } },
    { name: 'firefox',  use: { ...devices['Desktop Firefox'] } },
    { name: 'webkit',   use: { ...devices['Desktop Safari'] } },
    // Pure API project — runs the same baseURL with no browser.
    {
      name: 'api',
      testDir: './e2e/api',
      testMatch: ['**/*.spec.ts', '**/*.spec.js'],
      use: { baseURL: BASE_URL },
    },
    // Visual regression project (opt-in via @visual tag)
    {
      name: 'visual',
      grep: /@visual/,
      use: { ...devices['Desktop Chrome'] },
    },
  ],

  webServer: process.env.PLAYWRIGHT_NO_SERVER ? undefined : {
    command: 'bun run dev || npm run dev',
    url: BASE_URL,
    reuseExistingServer: !process.env.CI,
    timeout: 120_000,
  },
});
