// Generated by e2e-tests/setup.sh
// Replace this example with real specs (use write.sh <use-case-id> to scaffold from .s5d/scenarios/).
import { test, expect } from '@playwright/test';

test.describe('@use-case:example  homepage smoke', () => {
  test('homepage loads', async ({ page }) => {
    await page.goto('/');
    await expect(page).toHaveTitle(/.*/, { timeout: 10_000 });
  });

  test('@critical primary CTA is visible', async ({ page }) => {
    await page.goto('/');
    // TODO: pick a stable selector and adjust:
    // const cta = page.getByRole('link', { name: /get started/i });
    // await expect(cta).toBeVisible();
    expect.fail('TODO: write a real critical-path assertion');
  });
});
