// Generated by unit-tests/write.sh on {{TIMESTAMP}}
// Source under test: {{SOURCE_PATH}}
//
// TODO fill in real subtests and delete this comment.

package {{MODULE}}_test

import (
	"testing"
	// {{MODULE}} "path/to/{{MODULE}}"
)

func TestHappyPath(t *testing.T) {
	t.Run("TODO_describe_canonical_behaviour", func(t *testing.T) {
		// arrange
		// act
		// assert
		got := true
		if !got {
			t.Errorf("expected true, got %v", got)
		}
	})
}

func TestEdgeCases(t *testing.T) {
	cases := []struct {
		name string
		in   any
		want any
	}{
		// {name: "empty input", in: ..., want: ...},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Skip("TODO")
		})
	}
}
