// API-only Playwright spec (runs in the `api` project, no browser).
// Generated by e2e-tests/setup.sh — replace this example with real specs.
import { test, expect } from '@playwright/test';

test.describe('@use-case:example  API smoke', () => {
  test('@critical health endpoint returns 200', async ({ request }) => {
    const r = await request.get('/api/health');
    expect(r.status()).toBe(200);
    const body = await r.json();
    expect(body).toHaveProperty('status');
  });

  test('rejects unauthenticated request', async ({ request }) => {
    const r = await request.get('/api/user/profile');
    expect([401, 403]).toContain(r.status());
  });
});
