#!/usr/bin/env bash
# adr.sh — write an Architecture Decision Record skeleton for the chosen
# variant. Lands as a fresh s5d decision spec in .s5d/packages/ so it
# can be reviewed via the s5d skill (s5d_validate, s5d_preview, ...).
#
# Usage:
#   bash adr.sh queue --chose nats_jetstream --decided-by Roman \
#                     --rationale "low ops, sub-ms latency, cross-region edges"
#
# Required:
#   <commodity>     e.g. queue, cache, search
#   --chose <id>    variant id from templates/decisions/<commodity>.yaml
#   --decided-by    name of the human who confirmed
#   --rationale     one-paragraph justification

set -uo pipefail

SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DECISIONS_DIR="$SKILL_DIR/templates/decisions"

if [ $# -lt 1 ]; then
    echo "usage: $0 <commodity> --chose <variant-id> --decided-by <name> --rationale <text>" >&2
    exit 2
fi

COMMODITY="$1"; shift
CHOSEN=""
DECIDED_BY=""
RATIONALE=""
OUTPUT=""
ANSWERS_FILE=""

while [ $# -gt 0 ]; do
    case "$1" in
        --chose)      CHOSEN="$2"; shift 2 ;;
        --decided-by) DECIDED_BY="$2"; shift 2 ;;
        --rationale)  RATIONALE="$2"; shift 2 ;;
        --output)     OUTPUT="$2"; shift 2 ;;
        --answers)    ANSWERS_FILE="$2"; shift 2 ;;
        *) echo "unknown arg: $1" >&2; exit 2 ;;
    esac
done

[ -z "$CHOSEN" ]     && { echo "--chose is required" >&2; exit 2; }
[ -z "$DECIDED_BY" ] && { echo "--decided-by is required" >&2; exit 2; }
[ -z "$RATIONALE" ]  && { echo "--rationale is required" >&2; exit 2; }

YAML="$DECISIONS_DIR/${COMMODITY}.yaml"
[ ! -f "$YAML" ] && { echo "no decision frame: $COMMODITY" >&2; exit 2; }

# Pull the chosen variant's metadata (name, kind, notes) via python.
command -v python3 >/dev/null 2>&1 || { echo "python3 required" >&2; exit 2; }

# Default output path follows s5d conventions
DEC_ID="decision.${COMMODITY}-choice"
[ -z "$OUTPUT" ] && OUTPUT=".s5d/packages/${DEC_ID}.s5d.yaml"

mkdir -p "$(dirname "$OUTPUT")"

NOW=$(date -u +%Y-%m-%dT%H:%M:%SZ)
PRODUCT=$(basename "$(pwd)")

VARIANT_BLOB=$(python3 - "$YAML" "$CHOSEN" <<'PYEOF'
import sys
fn, target = sys.argv[1], sys.argv[2]
with open(fn) as f: text = f.read()
in_variant = False
indent_base = None
out = []
for line in text.split('\n'):
    stripped = line.lstrip()
    if stripped.startswith('- id:'):
        vid = stripped.split(':',1)[1].strip()
        if vid == target:
            in_variant = True
            indent_base = len(line) - len(stripped)
            out.append(line)
            continue
        if in_variant: break
    if in_variant:
        if line.strip() and (len(line) - len(stripped) <= indent_base) and not stripped.startswith('-'):
            break
        out.append(line)
print('\n'.join(out))
PYEOF
)

# Compose the ADR / s5d decision spec.
cat > "$OUTPUT" <<YAMLEOF
# Architecture Decision Record — generated by system-design/adr.sh.
# Treat this as an s5d decision-tier spec; review with the s5d skill.
schema: '1.0'
id: ${DEC_ID}
tier: decision
product: ${PRODUCT}
question: |
  Which ${COMMODITY} variant should we use, given the constraints captured
  during the system-design interview?
created_at: '${NOW}'

context: |
  Decision frame: ${COMMODITY} (see ~/.agents/skills/system-design/templates/decisions/${COMMODITY}.yaml)
  Chosen variant: ${CHOSEN}
  Confirmed by: ${DECIDED_BY}
$(if [ -n "$ANSWERS_FILE" ] && [ -f "$ANSWERS_FILE" ]; then
    echo "  Interview answers stored at: ${ANSWERS_FILE}"
fi)

decision: |
  ${RATIONALE}

chosen:
${VARIANT_BLOB}

# Hypotheses considered (fill in via s5d_add_hypothesis to formalise):
hypotheses:
  - id: ${CHOSEN}
    decision: winner
$(python3 - "$YAML" "$CHOSEN" <<'PYEOF'
import sys
fn, chosen = sys.argv[1], sys.argv[2]
with open(fn) as f: text = f.read()
ids = []
for line in text.split('\n'):
    s = line.lstrip()
    if s.startswith('- id:'):
        ids.append(s.split(':',1)[1].strip())
for i in ids:
    if i != chosen:
        print(f"  - id: {i}")
        print(f"    decision: rejected")
PYEOF
)

# Consequences (fill in before running s5d_decide via MCP):
consequences:
  - operational: "TODO — what does ${DECIDED_BY} now own ops-wise?"
  - financial:   "TODO — monthly cost estimate"
  - lock_in:     "TODO — exit cost if we want to switch in 2 years"
  - team:        "TODO — onboarding / training cost"

# Next steps once this ADR is approved:
#   1. s5d state preview ${OUTPUT}
#   2. s5d state approve ${OUTPUT} --reviewer ${DECIDED_BY}
#   3. Implement the chosen variant.
#   4. s5d state import ${OUTPUT} --verified-by <reviewer-different-from-approver>
YAMLEOF

echo "✓ wrote $OUTPUT" >&2
echo "  next: review with the s5d skill — s5d_preview / s5d_approve" >&2
