<?php
// Generated by unit-tests/write.sh on {{TIMESTAMP}}
// Source under test: {{SOURCE_PATH}}

declare(strict_types=1);

namespace Tests\Unit;

use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;

final class {{MODULE}}Test extends TestCase
{
    protected function setUp(): void
    {
        // arrange shared state
    }

    #[Test]
    public function happyPathTodo(): void
    {
        // arrange
        // act
        // assert
        $this->assertTrue(true, 'TODO: real assertion');
    }

    public static function edgeCasesProvider(): array
    {
        return [
            // ['input' => '', 'expected' => null],
        ];
    }

    #[Test]
    #[DataProvider('edgeCasesProvider')]
    public function edgeCasesTodo(string $input, mixed $expected): void
    {
        $this->markTestIncomplete('TODO');
    }
}
