# .simplecov — generated by unit-tests skill. Loaded automatically by SimpleCov.
SimpleCov.start do
  add_filter '/spec/'
  add_filter '/test/'
  add_filter '/vendor/'
  add_filter '/config/'
  add_filter '/db/migrate/'

  enable_coverage :branch
  primary_coverage :line

  coverage_dir 'test-reports/ruby/coverage'
  formatter SimpleCov::Formatter::MultiFormatter.new([
    SimpleCov::Formatter::HTMLFormatter,
    SimpleCov::Formatter::SimpleFormatter,
  ])

  minimum_coverage line: {{THRESHOLD}}, branch: 60
  minimum_coverage_by_file line: 50
end
