# Generated by unit-tests/write.sh on {{TIMESTAMP}}
# Source under test: {{SOURCE_PATH}}

require 'spec_helper'
# require '{{MODULE}}'

RSpec.describe '{{MODULE}}' do
  before do
    # arrange shared state
  end

  describe 'happy path' do
    it 'TODO: describes canonical behaviour' do
      # arrange
      # act
      # assert
      expect(true).to eq(true)
    end
  end

  describe 'edge cases' do
    it 'TODO: write what should break'
    it 'TODO: write what should reject'
  end
end
