#!/usr/bin/env bats
# Generated by unit-tests/write.sh on {{TIMESTAMP}}
# Source under test: {{SOURCE_PATH}}

setup() {
    # load 'test_helper/bats-support/load'
    # load 'test_helper/bats-assert/load'
    SOURCE_DIR="$(cd "$(dirname "$BATS_TEST_FILENAME")" && pwd)"
    # source the script under test:
    # source "$SOURCE_DIR/{{MODULE}}.sh"
    :
}

@test "happy path — TODO describe canonical behaviour" {
    # arrange
    # act
    run echo "ok"
    # assert
    [ "$status" -eq 0 ]
    [ "$output" = "ok" ]
}

@test "edge case — TODO write what should break" {
    skip "TODO"
}

@test "failure mode — TODO write what should reject" {
    skip "TODO"
}
