// Generated by unit-tests/write.sh on {{TIMESTAMP}}
// Source under test: {{SOURCE_PATH}}

import Testing
// @testable import {{MODULE}}

@Suite("{{MODULE}}")
struct {{MODULE}}Tests {

    @Test("happy path — TODO describe canonical behaviour")
    func happyPathTodo() async throws {
        // arrange
        // act
        // assert
        #expect(true, "TODO: real assertion")
    }

    @Test("parametric edge cases", arguments: [0, 1, 2])
    func edgeCasesTodo(value: Int) async throws {
        // TODO
    }
}
