"""Generated by unit-tests/write.sh on {{TIMESTAMP}}.

Source under test: {{SOURCE_PATH}}

TODO replace the placeholder bodies with real assertions and delete this docstring.
"""
import pytest

# from {{MODULE}} import ...


class TestModule:
    """Group tests for the {{MODULE}} module."""

    def setup_method(self) -> None:
        """Arrange shared state for each test."""

    def test_happy_path_TODO(self) -> None:
        """TODO: describe canonical behaviour."""
        # arrange
        # act
        # assert
        assert True

    @pytest.mark.xfail(reason="not implemented yet")
    def test_edge_case_TODO(self) -> None:
        """TODO: write what should break."""
        raise NotImplementedError

    @pytest.mark.xfail(reason="not implemented yet")
    def test_failure_mode_TODO(self) -> None:
        """TODO: write what should reject."""
        raise NotImplementedError
