// Generated by unit-tests/write.sh on {{TIMESTAMP}}
// Source under test: {{SOURCE_PATH}}

package com.example;   // TODO match the package of the source-under-test

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

import static org.junit.jupiter.api.Assertions.*;

@DisplayName("{{MODULE}}")
class {{MODULE}}Test {

    @BeforeEach
    void setUp() {
        // arrange shared state
    }

    @Test
    @DisplayName("happy path — describe canonical behaviour")
    void happyPathTodo() {
        // arrange
        // act
        // assert
        assertTrue(true, "TODO: real assertion");
    }

    @ParameterizedTest
    @ValueSource(ints = {0, 1, 2})
    @DisplayName("parametric — edge values")
    void edgeCasesTodo(int input) {
        // TODO
    }
}
