#!/usr/bin/env bash
# write.sh — scaffold an e2e spec from a .s5d/scenarios/<id>.feature file.
#
# The .feature file (produced by scenario-mine) becomes a Playwright spec
# with one test() per Scenario, tagged @use-case:<id> for coverage tracking.
# Stubs contain TODO markers so they fail until filled in.
#
# Usage:
#   bash write.sh apply-for-event-insurance              # web (default)
#   bash write.sh apply-for-event-insurance --axis api
#   bash write.sh apply-for-event-insurance --axis mobile

set -uo pipefail

SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

USE_CASE=""
AXIS="web"

while [ $# -gt 0 ]; do
    case "$1" in
        --axis)    AXIS="$2"; shift 2 ;;
        -h|--help)
            sed -n '2,10p' "${BASH_SOURCE[0]}" | sed 's/^# \?//'
            exit 0
            ;;
        -*)        echo "unknown flag: $1" >&2; exit 2 ;;
        *)         USE_CASE="$1"; shift ;;
    esac
done

[ -z "$USE_CASE" ] && { echo "usage: $0 <use-case-id> [--axis web|api|mobile]" >&2; exit 2; }

FEATURE=".s5d/scenarios/${USE_CASE}.feature"
[ ! -f "$FEATURE" ] && {
    echo "→ no feature file: $FEATURE" >&2
    echo "  Run scenario-mine first to produce it." >&2
    exit 2
}

case "$AXIS" in
    web)
        DST="e2e/${USE_CASE}.spec.ts"
        TEMPLATE_HEADER="import { test, expect } from '@playwright/test';"
        ;;
    api)
        DST="e2e/api/${USE_CASE}.api.spec.ts"
        TEMPLATE_HEADER="import { test, expect } from '@playwright/test';"
        ;;
    mobile)
        DST=".maestro/${USE_CASE}.yaml"
        ;;
    *) echo "unknown axis: $AXIS" >&2; exit 2 ;;
esac

[ -e "$DST" ] && {
    echo "  ! destination exists: $DST — inspect and merge manually" >&2
    exit 1
}

NOW=$(date -u +%Y-%m-%dT%H:%M:%SZ)
mkdir -p "$(dirname "$DST")"

# Pull Feature title + Scenarios from the .feature.
FEATURE_TITLE=$(grep -m1 '^Feature:' "$FEATURE" | sed 's/^Feature:[[:space:]]*//')
DOMAIN=$(grep -m1 '^@s5d-domain:' "$FEATURE" | sed 's/^@s5d-domain://; s/[[:space:]]*$//')

# Extract scenario names (Scenario: and Scenario Outline:) + their @kind / @source tags above.
# Approach: read the file linewise, accumulate tags + emit when a scenario header appears.

write_web_or_api() {
    cat > "$DST" <<HEADER
// Generated by e2e-tests/write.sh on $NOW
// Source: $FEATURE
// Use case: $USE_CASE (domain: $DOMAIN)
//
// One test() per Scenario in the feature file. Fill in the TODO bodies and
// delete this comment block once each scenario is real.

$TEMPLATE_HEADER

test.describe('@use-case:$USE_CASE  $FEATURE_TITLE', () => {
HEADER

    # Walk the feature file, find scenarios, emit one test() per Scenario.
    # Tags above a Scenario line accumulate; reset after emit; non-tag /
    # non-scenario lines (Background, Given/When/Then) clear pending tags
    # so they do not bleed into the next scenario.
    awk -v use_case="$USE_CASE" '
        { trimmed = $0; sub(/^[[:space:]]+/, "", trimmed) }
        trimmed ~ /^@/ {
            tags = tags " " trimmed
            next
        }
        trimmed ~ /^Scenario( Outline)?:/ {
            name = trimmed
            sub(/^Scenario( Outline)?:[[:space:]]*/, "", name)
            gsub(/"/, "\\\"", name)
            gsub(/^[[:space:]]+|[[:space:]]+$/, "", tags)
            n = split(tags, parts, /[[:space:]]+/)
            tag_csv = ""
            for (i = 1; i <= n; i++) {
                t = parts[i]
                if (t == "") continue
                sub(/^@/, "", t)
                if (tag_csv != "") tag_csv = tag_csv ", "
                tag_csv = tag_csv "\"@" t "\""
            }
            print ""
            print "    test(\"" name "\", { tag: [" tag_csv "] }, async ({ page, request }) => {"
            print "        // From scenario: " name
            print "        // TODO: implement steps from the .feature file."
            print "        expect.fail(\"TODO: implement this scenario\");"
            print "    });"
            tags = ""
            next
        }
        trimmed == "" { next }
        { tags = "" }
    ' "$FEATURE" >> "$DST"

    echo "});" >> "$DST"
}

write_maestro() {
    cat > "$DST" <<HEADER
# Generated by e2e-tests/write.sh on $NOW
# Source: $FEATURE
# Use case: $USE_CASE (domain: $DOMAIN)
#
# Maestro flow. Maestro runs one flow per file — pick the most critical
# scenario from the feature file. For additional scenarios, write more
# flow files under .maestro/${USE_CASE}.<slice>.yaml.

appId: TODO.replace.with.app.id
name: $USE_CASE
tags:
  - use-case:$USE_CASE
  - domain:$DOMAIN
---
# TODO: replicate the canonical scenario from $FEATURE here.
# Common Maestro commands:
#   - launchApp
#   - tapOn: "Continue"
#   - inputText: "..."
#   - assertVisible: "..."
#   - takeScreenshot: name
- launchApp
- assertVisible: "TODO replace with first observable state"
HEADER
}

case "$AXIS" in
    web|api)  write_web_or_api ;;
    mobile)   write_maestro ;;
esac

echo "✓ wrote $DST" >&2
echo "  next: open $DST, fill in TODOs, then run:" >&2
echo "        bash $SKILL_DIR/scripts/run.sh --axes $AXIS" >&2
