#!/usr/bin/env bash
# generate.sh — produce machine-readable doc artifacts from the current inventory:
#   - llms.txt  (the llms.txt standard: H1 title + summary blockquote + curated links)
#   - docs index (table of contents linking every doc, grouped by directory)
#
# READ-ONLY on existing docs: it reads them and WRITES the two generated artifacts to a
# staging dir (default test-reports/docs/) so nothing existing is clobbered. Use --apply
# to instead write llms.txt to repo root and the index to docs/index.md (review first).
#
#   bash generate.sh            # → test-reports/docs/{llms.txt,index.md} (staging)
#   bash generate.sh --save     # same, explicit
#   bash generate.sh --apply    # → ./llms.txt and ./docs/index.md (mutates repo)

set -uo pipefail
ROOT="$(pwd)"; APPLY=0
while [ $# -gt 0 ]; do
    case "$1" in --apply) APPLY=1; shift ;; --save) shift ;; --root) ROOT="$2"; shift 2 ;; *) shift ;; esac
done
cd "$ROOT"
command -v python3 >/dev/null 2>&1 || { echo "python3 required" >&2; exit 2; }

md_list() {
    find . -type d \( -name node_modules -o -name .git -o -name vendor -o -name target \
        -o -name build -o -name dist -o -name .next -o -name .venv -o -name __pycache__ \
        -o -name .claude -o -name .codex -o -name .agents -o -name test-reports \
        -o -name .playwright-browsers \) -prune \
        -o -type f -name '*.md' -print 2>/dev/null | sed 's|^\./||' | sort
}
TITLE="$(basename "$ROOT")"
[ -f README.md ] && t="$(grep -m1 '^# ' README.md 2>/dev/null | sed 's/^# //')" && [ -n "$t" ] && TITLE="$t"

MDS="$(md_list)"
MDFILE="$(mktemp)"
printf '%s\n' "$MDS" > "$MDFILE"
python3 - "$TITLE" "$MDFILE" <<'PYEOF'
import sys, os
title = sys.argv[1]
mds = [l for l in open(sys.argv[2], encoding="utf-8", errors="ignore").read().splitlines() if l.strip()]
def doc_title(p):
    try:
        for line in open(p, encoding="utf-8", errors="ignore"):
            if line.startswith("# "): return line[2:].strip()
    except Exception: pass
    return os.path.basename(p).rsplit(".",1)[0].replace("_"," ").replace("-"," ")
# group by top-level dir
groups = {}
for p in mds:
    top = p.split("/")[0] if "/" in p else "(root)"
    groups.setdefault(top, []).append(p)

# ---- llms.txt ----
out_llms = []
out_llms.append(f"# {title}\n")
out_llms.append(f"> Machine-readable index of {len(mds)} documentation files for this project. "
                f"Generated by ai-technical-writer; curate descriptions and prune before publishing.\n")
for g in sorted(groups):
    out_llms.append(f"## {g}\n")
    for p in sorted(groups[g]):
        out_llms.append(f"- [{doc_title(p)}]({p}): {os.path.basename(p)}")
    out_llms.append("")
open("/tmp/_gen_llms.txt","w").write("\n".join(out_llms))

# ---- docs index ----
out_idx = []
out_idx.append(f"# {title} — Documentation Index\n")
out_idx.append(f"_Auto-generated table of contents ({len(mds)} docs). Every doc should be reachable from here._\n")
for g in sorted(groups):
    out_idx.append(f"## {g}\n")
    for p in sorted(groups[g]):
        out_idx.append(f"- [{doc_title(p)}]({p})")
    out_idx.append("")
open("/tmp/_gen_index.md","w").write("\n".join(out_idx))
print(f"{len(mds)} docs · {len(groups)} groups")
PYEOF
rm -f "$MDFILE" 2>/dev/null || true

if [ "$APPLY" -eq 1 ]; then
    cp /tmp/_gen_llms.txt llms.txt
    mkdir -p docs && cp /tmp/_gen_index.md docs/index.md
    echo "✓ applied: ./llms.txt and ./docs/index.md (review + curate the descriptions)" >&2
else
    mkdir -p test-reports/docs
    cp /tmp/_gen_llms.txt test-reports/docs/llms.txt
    cp /tmp/_gen_index.md test-reports/docs/index.md
    echo "✓ staged: test-reports/docs/{llms.txt,index.md} (review, then re-run with --apply)" >&2
fi
rm -f /tmp/_gen_llms.txt /tmp/_gen_index.md 2>/dev/null || true
