// kover-snippet.gradle.kts — generated by unit-tests skill.
// Merge into your top-level build.gradle.kts. Threshold: {{THRESHOLD}}% line coverage.

plugins {
    id("org.jetbrains.kotlinx.kover") version "0.9.0"
}

kover {
    reports {
        verify {
            rule {
                minBound({{THRESHOLD}})
            }
        }
        total {
            xml { onCheck = true }
            html { onCheck = true }
        }
        filters {
            excludes {
                classes("*.generated.*", "*Test", "*Tests", "*Spec")
            }
        }
    }
}
